### ISSUE TITLE
Doesn't seem to work with workspaces

### ISSUE THREAD

**Issue by ctessier** [joakimen/node-run#1]
Hi,

I have a monorepo with workspaces but only the scripts in the root `package.json` are listed.
I understand this project is supposed to support workspaces but it doesn't seem to work.

Workspaces are declared as such: https://docs.npmjs.com/cli/v7/using-npm/workspaces

```json
"workspaces": [
  "apps/*",
  "configs/*",
  "firebase/*",
  "libs/*"
],
```

Thank you for your help

**Comment by joakimen** [comment]
Hi @ctessier,

Apologies for the confusing description. Only listing scripts in the current package is the intended behaviour. What I meant by supporting workspaces is being able to parse `npm` output when parsing scripts in regular and workspace-style projects, not listing and running scripts across root and child packages.

Running scripts from child packages would involve way more complexity than it's worth (detecting child packages, asynchronously detecting scripts, rendering them interactively in a practical manner, ..) so I intend to keep it this way for simplicity. 

I [updated the README](https://github.com/joakimen/node-run/commit/fdcbce00ca6df7fed79ed139cc7d6d9244ea51c9) to clarify.
